# Generated by Django 4.2.5 on 2023-11-24 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_status',
        ),
    ]
