# Generated by Django 4.2.5 on 2023-11-24 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_orders_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('Shipping_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('shipping_email', models.EmailField(max_length=254)),
                ('shipping_address', models.CharField(max_length=255)),
                ('shipping_phonenumber', models.CharField(max_length=20)),
                ('shipping_description', models.CharField(max_length=255)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.orders')),
            ],
        ),
    ]
